services:
  postrgesql:
    image: 'postgres:latest'
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    container_name: 'postgredb'
    ports:
      - 15432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data/

  pgadmin:
    image: 'dpage/pgadmin4:latest'
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
    ports:
      - 15080:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin/

volumes:
  pg-data:
  pgadmin-data: